services:
  - type: web
    runtime: docker
    name: Deploy
    plan: free
    branch: main
    rootDir: .
    dockerCommand: bash start.sh
    repo: https://github.com/baqir-batch/Deploy.git
    region: frankfurt
    envVars:
      - key: API_ID
        value: 13740761
      - key: API_HASH
        value: 4ce319a92c01fab2b02551af8d7f73a4
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Baghdad
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    plan: free
    region: frankfurt
